version: '3.4'

services:
#  webapplication.api:
#    image: webapplicationapi
#    build:
#      context: .
#      dockerfile: WebApplication.API/Dockerfile
#    ports:
#     - "8005:80"     
#    networks:
#      logmetric:

 # blazorapp1:
 #   image: blazorapp1
 #   build:
 #     context: .
 #     dockerfile: BlazorApp1/Dockerfile
 #   ports:
 #    - "8004:80"
 #   networks:
 #     logmetric:

#  zipkin:
#    image: "openzipkin/zipkin"
#    ports:
#      - "9411:9411"
#    networks:
#      logmetric:   

  seq:
    image: "datalust/seq"
    ports:
      - "8080:80"
      - "5341:5341" 
    environment:
      - ACCEPT_EULA=Y
    networks:
      logmetric:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
    ports:
      - 9200:9200
   # volumes:
   #  - elasticsearch-data:C:\data
    networks:
      logmetric:
  
  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.0
    ports:
      - 5601:5601
    depends_on:
    - elasticsearch
    networks:
      logmetric:

#  influxdb:
#    image: influxdb
#    ports:
#      - 8086:8086
#    networks:
#      logmetric:
#
#  grafana:
#    image: grafana/grafana
#    ports:
#      - 3000:3000
#    depends_on:
#    - influxdb
#    networks:
#      logmetric:
#
networks:
 logmetric:
   driver: 'bridge'  

#volumes:
#  elasticsearch-data: